name: "Requerimiento de Software (RQA)"
description: Formato estándar para elicitación de requisitos.
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción del Requisito
      placeholder: "Como [rol], quiero [funcionalidad] para [beneficio]..."
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: Criterios de Aceptación
      description: "Desglose los criterios usando listas de verificación (- [ ])."
      placeholder: |
        - [ ] Criterio de rendimiento (ej. < 2s)...
        - [ ] Criterio de seguridad...
    validations:
      required: true
