name: "Requerimiento de Software (RQA)"
description: Formato estándar para elicitación de requisitos.
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción del Requisito
      placeholder: "Como [rol], quiero [funcionalidad] para [beneficio]..."
    validations:
      required: true
  - type: input
    id: criteria
    attributes:
      label: Criterio de Aceptación
      placeholder: "Debe permitir subir archivos PDF de máximo 5MB"
    validations:
      required: true